# AROI semseg config

# Finetune from:
finetune: './_weights/v3_multimae-b_pret-multimae_49_1600e_bscan_512-32_checkpoint-1599.pth'

# Input tasks
in_domains: bscan

mapping:
  0: 0
  23: 1
  46: 2
  69: 3
  92: 4
  115: 5
  138: 6
  161: 7

# Architecture
model: multivit_base
patch_size:
  bscan: [32, 32]
num_global_tokens: 1
drop_path_encoder: 0.1
output_adapter: convnext
decoder_main_tasks: bscan
decoder_dim: 6144
decoder_preds_per_patch: 16
decoder_depth: 4

# Train
epochs: 200
opt: adamw
lr: 0.0001 # = 1e-4
warmup_lr: 0.000001 # = 1e-6
min_lr: 0.
warmup_epochs: 1
batch_size: 4
input_size:
  bscan: [1024, 1024]
layer_decay: 0.75

# Augmentation
aug_name: simple

# Data info
data_path: '/msc/home/jmoran82/FullVIBES-v2/Downstream_seg_datasets/AROI_2D/train'
eval_data_path: '/msc/home/jmoran82/FullVIBES-v2/Downstream_seg_datasets/AROI_2D/val'
num_classes: 8
dataset_name: AROI
seg_reduce_zero_label: False
dist_eval: False
eval_freq: 1
log_images: False

# Misc.
find_unused_params: False

# Wandb and logging
log_wandb: False # Set to True to log to Weights & Biases
wandb_project: 'multimae-finetune-semseg'
wandb_entity: null # Change if needed
wandb_run_name: 'ft_aroi_200e_multimae-b_bscan'
log_images_wandb: False
log_images_freq: 20
output_dir: 'output/finetune/semseg/AROI_2D/ft_aroi_200e_multimae-b_bscan-baseline_bscan'
