# RETOUCH semseg config

# Finetune from:
finetune: './_weights/dinov2_vitl14_pretrain.pth'

# Input tasks
in_domains: bscan

mapping:
  0: 0
  85: 1
  170: 2
  255: 3

# Architecture
model: multivit_large
patch_size:
  bscan: [32, 32]
num_global_tokens: 1
drop_path_encoder: 0.1
output_adapter: convnext
decoder_main_tasks: bscan
decoder_dim: 6144
decoder_preds_per_patch: 16
decoder_depth: 4

# Train
epochs: 200
opt: adamw
lr: 0.0001 # = 1e-4
warmup_lr: 0.000001 # = 1e-6
min_lr: 0.
warmup_epochs: 1
batch_size: 4
input_size:
  bscan: [1024, 1024]
layer_decay: 0.75

# Augmentation
aug_name: simple

# Data info
data_path: '/msc/home/jmoran82/FullVIBES-v2/Downstream_seg_datasets/RETOUCH_2D/train'
eval_data_path: '/msc/home/jmoran82/FullVIBES-v2/Downstream_seg_datasets/RETOUCH_2D/val'
# test_data_path: '/msc/home/jmoran82/FullVIBES-v2/Downstream_seg_datasets/RETOUCH_2D/Standard_test_images'
num_classes: 4
dataset_name: RETOUCH_2D
seg_reduce_zero_label: False
dist_eval: False
eval_freq: 1
log_images: False

# Misc.
find_unused_params: False

# Wandb and logging
log_wandb: False # Set to True to log to Weights & Biases
wandb_project: 'multimae-finetune-semseg'
wandb_entity: null # Change if needed
wandb_run_name: 'ft_retouch_200e_dinov2-l_bscan'
log_images_wandb: False
log_images_freq: 20
output_dir: 'output/finetune/semseg/RETOUCH_2D/ft_retouch_200e_dinov2-l_bscan'
