# Finetune from:
finetune: './_weights/v3_multimae-b_pret-multimae_98_1600e_bscan-slo-bscanlayermap_512-128--32-8_checkpoint-1599.pth'

# Model
model: multivit_base
patch_size: 32
use_mean_pooling: True
drop_path: 0.1

# Train
epochs: 100
opt: adamw
blr: 0.0005  # 5e-4
weight_decay: 0.05
warmup_epochs: 5
batch_size: 32
input_size: 512
dist_eval: True
layer_decay: 0.65
nb_classes: 2

# Data
#
data_set: 'image_folder'
data_path: '/path/to/data'
eval_data_path: '/path/to/data'

# Wandb logging
log_wandb: False # Set to True to activate logging to Weights & Biases
wandb_project: 'multimae-finetune-cls'
wandb_entity: null # Change if needed
wandb_run_name: ft_in1k_100e_multimae-b
output_dir: 'output/finetune/cls/ft_harvard-glaucoma_100e_multimae-b'
